### ISSUE TITLE
Question: Any plans to add the alternative form controls (switch, radio, checkbox)?

### ISSUE THREAD

**Issue by alex996** [Wikiki/bulma-divider#1]
Just stumbled upon your Bulma extensions and they seem very nice! I was curious though, do you have those switch, radio, or checkbox controls shown in the screenshot of this package? I'm particularly interested in the switch. Do you have any plans to publish it and/or submit to the [Bulma extensions list](http://bulma.io/extensions/)?

Thanks!

**Comment by Wikiki** [comment]
Hi,

I just commit a new extension to design checkboxes.
You can find it here: https://github.com/Wikiki/bulma-switch
I changed the design a little bit comparing to the one on my screenshot. But I will be glad to help you to get the previous design if you want to.

regards
