### ISSUE TITLE
Please don't release breaking changes under minor version bump

### ISSUE THREAD

**Issue by cyrilchapon** [Wikiki/bulma-divider#10]
[Semver](https://semver.org/) is very strict regarding breaking or non breaking, but when it comes to CSS, this is less crystal clear because there is no real "API".

Changing a behavior under the same API (and talking about CSS, a single class is an API) could be seen as a breaking backward compatibility change.

Changing `display` from `block` to `flex`, and setting `flex-grow: 1` on it is a dangerous operation, and should not, IMHO, be taken as a minor release.

When upgrading (not manually, but with default npm policy regarding Semver, `^1.0.1`) from 1.0.1 to 1.0.4 It broke our layout, and apparently, we're [not the only ones in that case](https://github.com/Wikiki/bulma-divider/issues/9)

Yes we should be shrinkwrapping, package-locking or using yarn, but that's not a reason not to follow versioning best practises 😄

**Comment by Wikiki** [comment]
My bad. Sorry for the inconvenience. I'll be more carefull to it next time.

**Comment by Wikiki** [comment]
Except for the versioning which will be take into account better next time. Can you please confirm everything's now fine with the version 1.0.5 ?

**Comment by cyrilchapon** [comment]
I don't have a clue, I spent the whole morning reverting that xD
