### ISSUE TITLE
vertical divider: any way to make it horizontal or invisible on mobile?

### ISSUE THREAD

**Issue by empresarrollo** [Wikiki/bulma-divider#3]
if you have 3 columns with 2 vertical dividers, when you make the screen smaller and the columns get stacked, you still see the vertical divider. It would be great if there is a class to make it horizontal on mobile, or just make it dissapear.

**Comment by echohive** [comment]
I'd love this too - it's probably the standout tidbit of Semantic UI, and would love to be able to use that in Bulma too 🙂

**Comment by Wikiki** [comment]
Fixed
