### ISSUE TITLE
How to overwrite the default line thickness?

### ISSUE THREAD

**Issue by MannikJ** [Wikiki/bulma-divider#6]
The title says it all. At first I thought overwriting the font size would also affect the thickness of the divider. So would it be possible to provide a variable for the thickness, or is there a better way?

**Comment by Wikiki** [comment]
Hi,

it's not available currently. But I like the idea. 
I'll see what I can do for it.

regards

**Comment by Wikiki** [comment]
You can now use the <code>$divider-thickness</code>
