### ISSUE TITLE
Vertical Divider Broken (?) in v1.0.4

### ISSUE THREAD

**Issue by MannikJ** [Wikiki/bulma-divider#9]
Hi,
I recently upgraded from v1.0.1 to v1.0.4 and noticed that the vertical divider behaves completely different than before. 
I don't know whether this is desired behavior, but at least I can say that my layouts are broken now and I would like to know how to get back the result as it was.
The gap is way to large and the line also does not go down to the end of the containers it divides.
Hope there is a quick fix or hint how to solve it soon!

Best regards and thanks for the great work!

**Comment by Wikiki** [comment]
Hi,

sorry about that.
You can use the 1.0.3: https://github.com/Wikiki/bulma-divider/releases/tag/1.0.3 version waiting I fix the issue.

**Comment by Wikiki** [comment]
Can you please confirm everything's now fine with the version 1.0.5 ?

**Comment by MannikJ** [comment]
@Wikiki  
It's ok with v1.0.5. Thank you!

**Comment by Wikiki** [comment]
I'm glad to hear it :-D
